-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS transfers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_account_id bigint NOT NULL,
    to_account_id bigint NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (from_account_id) REFERENCES accounts(id),
    FOREIGN KEY (to_account_id) REFERENCES accounts(id)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS transfers;
-- +goose StatementEnd
