-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS account_balance_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL,
    balance decimal(20, 6) NOT NULL,
    last_transaction_id bigint NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES accounts(id)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS account_balance_snapshots;
-- +goose StatementEnd
