// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package sqlc

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, created_at, updated_at)
VALUES ($1, NOW(), NOW())
RETURNING id, created_at, updated_at
`

func (q *Queries) CreateAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, id)
	var i Account
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getAccountBalanceByAccountID = `-- name: GetAccountBalanceByAccountID :one
WITH filters AS (
    SELECT
        $1 as account_id
),
latest_snapshot AS (
    SELECT 
        account_balance_snapshots.account_id,
        balance,
        last_transaction_id,
        created_at
    FROM account_balance_snapshots
    JOIN filters ON account_balance_snapshots.account_id = filters.account_id
    ORDER BY created_at DESC
    LIMIT 1
),
recent_transactions AS (
    SELECT 
        COALESCE(
            SUM(CASE 
                WHEN t.trx_type = 'CREDIT' THEN t.amount
                WHEN t.trx_type = 'DEBIT' THEN -t.amount
                ELSE 0
            END), 0
        ) as transaction_delta
    FROM transactions t
    CROSS JOIN latest_snapshot ls
    JOIN filters ON t.account_id = filters.account_id
      AND t.id > ls.last_transaction_id
)
SELECT
    ls.balance + COALESCE(rt.transaction_delta, 0) as current_balance
FROM latest_snapshot ls
CROSS JOIN recent_transactions rt
`

func (q *Queries) GetAccountBalanceByAccountID(ctx context.Context, accountID int64) (int32, error) {
	row := q.db.QueryRowContext(ctx, getAccountBalanceByAccountID, accountID)
	var current_balance int32
	err := row.Scan(&current_balance)
	return current_balance, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, created_at, updated_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
