// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CheckAccountExists(ctx context.Context, id int64) (bool, error)
	CreateAccount(ctx context.Context, id int64) (Account, error)
	CreateCreditTransaction(ctx context.Context, arg CreateCreditTransactionParams) (Transaction, error)
	CreateDebitTransaction(ctx context.Context, arg CreateDebitTransactionParams) (Transaction, error)
	GetAccountBalanceByAccountID(ctx context.Context, arg GetAccountBalanceByAccountIDParams) (string, error)
	GetAccountByID(ctx context.Context, id int64) (Account, error)
}

var _ Querier = (*Queries)(nil)
