// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, id int64) (Account, error)
	CreateCreditTransaction(ctx context.Context, arg CreateCreditTransactionParams) (Transaction, error)
	CreateDebitTransaction(ctx context.Context, arg CreateDebitTransactionParams) (Transaction, error)
	GetAccountByID(ctx context.Context, id int64) (Account, error)
}

var _ Querier = (*Queries)(nil)
